# Generated by Django 4.1.5 on 2023-01-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('java_vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='demand_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('aver_salary', models.IntegerField()),
                ('count', models.IntegerField()),
                ('year', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='geography_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('aver_salary', models.IntegerField()),
                ('share', models.FloatField()),
            ],
        ),
    ]
